Django/Mysite/Mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', login_view, name='login'),
    url(r'^register/', register_view, name='register'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^', include("main.urls", namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/Mysite/main/urls.py
from django.conf.urls import include, url
from django.contrib import admin

#from . import views

from .views import (
    post_main,
    post_chat,
    post_computer,
    post_movie,
    post_game,
    post_drama,
    post_mylog,
    post_detail,
    post_delete,
    post_suggest,
    post_create,
    post_update,
    )

urlpatterns = [
    url(r'^$', post_main, name='pmain'),
    url(r'^chat/$', post_chat, name='pchat'),
    url(r'^computer/$', post_computer, name='pcomputer'),
    url(r'^movie/$', post_movie, name='pmovie'),
    url(r'^game/$', post_game, name='pgame'),
    url(r'^drama/$', post_drama, name='pdrama'),
    url(r'^mylog/$', post_mylog, name='pmylog'),
    url(r'^suggest/$', post_suggest, name='psuggest'),
    url(r'^create/$', post_create, name='create'),
    url(r'^post/(?P<id>\d+)/edit/$', post_update, name='update'),
    url(r'^post/(?P<id>\d+)/$', post_detail, name='detail'),
    url(r'^post/(?P<id>\d+)/delete/$', post_delete, name='delete'),
]

Django/Mysite/main/models.py
# -*- coding: utf-8 -*- 
from __future__ import unicode_literals

from django.contrib.contenttypes.models import ContentType
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from comments.models import Comment

from django.utils.safestring import mark_safe
from markdown_deux import markdown


def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)

Classify_Choises = (
    ('잡담','잡담'),
    ('컴퓨터', '컴퓨터'),
    ('영화','영화'),
    ('게임','게임'),
    ('드라마','드라마'),
    ('문의','문의'),
)

class Post(models.Model):
	classify = models.CharField(max_length=10, choices=Classify_Choises, default='잡담')
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
	title = models.CharField(max_length=120)
	image = models.ImageField(upload_to=upload_location,
			null=True,
			blank=True, 
			width_field="width_field", 
			height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	content = models.TextField()
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("main:detail", kwargs={'id': self.id})
		
	def get_absolute_delete(self):
		return reverse("main:delete", kwargs={'id': self.id})

	class Meta:
		ordering = ["-timestamp", "-updated"]

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)

	@property
	def comments(self):
		instance = self
		qs =Comment.objects.filter_by_instance(instance)
		return qs
		
	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

	


# Create your models here.

Django/Mysite/accounts/forms.py
# -*- coding: utf-8 -*- 
from django import forms


from django.contrib.auth import(
	authenticate,
	get_user_model,
	login,
	logout,
	)

User = get_user_model()

class UserLoginForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-username form-control',
															 'name' : 'form-username',
															 'id' : 'form-username',
															 'placeholder' : 'Username...'
															 }), 
													label="")
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'form-password form-control',
																 'name' : 'form-password',
																 'id' : 'form-password',
															 	 'placeholder' : 'Password...'
															 	}),
													label="")

	def clean(self, *args, **kwargs):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")
		#user_qs = User.objects.filter(username=username)
		#if user_qs.count() = 1:
		#	user = user_qs.first()
		if username and password:
			user = authenticate(username=username, password=password)
			if not user:
				raise forms.ValidationError("등록되지 않은 아이디 입니다.")
			if not user.check_password(password):
				raise forms.ValidationError("패스워드가 틀렸습니다.")
			if not user.is_active:
				raise forms.ValidationError("사용불가능한 아이디 입니다.")
		return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
	email = forms.EmailField(label='Email Email')
	email2 = forms.EmailField(label='Confirm Email')
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = [
			'username',		
			'password',
			'email',
			'email2',
		]

#	def clena(self, *args, **kwargs):
#		email = self.cleaned_data.get('email')
#		email2 = self.cleaned_data.get('email2')
#		if email != email2:
#			raise forms.ValidationError("이메일이 동일하지 않습니다.")
#		email_qs = User.objects.filter(email=email)
#		if email_qs.exists():
#			raise forms.ValidationError("동일한 이메일이 존재합니다.")
#
#		return super(UserRegisterForm,self).clean(*args, **kwargs)

	def clean_email2(self):
		email = self.cleaned_data.get('email')
		email2 = self.cleaned_data.get('email2')
		if email != email2:
			raise forms.ValidationError("이메일이 동일하지 않습니다.")

		email_qs = User.objects.filter(email=email)
		if email_qs.exists():
			raise forms.ValidationError("동일한 이메일이 존재합니다.")
		return email

Django/Mysite/main/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post

class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	class Meta:
		model=Post
		fields = [
			"classify",
			"title",
			"content",
			"image",
		]

Django/Mysite/accounts/views.py
# -*- coding: utf-8 -*- 
from django.contrib.auth import(
	authenticate,
	get_user_model,
	login,
	logout,
	)
from django.shortcuts import render, redirect

from .forms import UserLoginForm, UserRegisterForm

def login_view(request):
	form = UserLoginForm(request.POST or None)
	if form.is_valid():
		username=form.cleaned_data.get("username")
		password=form.cleaned_data.get("password")
		user = authenticate(username=username, password=password)
		login(request, user)
		return redirect("/")
	context = {
		"form" : form,
		"title" : "Sign In",
		"subtitle": "Login to our site",
		"title2": "Welcome My Site",
		"subtitle2": "Enter your username, password",
		"controll" : '처음이십니까??',
		"controll_url" : "/register/",
	}

	return render(request, "accounts.html", context)

def register_view(request):
	print(request.user.is_authenticated())
	title = "Register"
	form = UserRegisterForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		password = form.cleaned_data.get('password')
		user.set_password(password)
		user.save()
		new_user = authenticate(username=user.username, password=password)
		login(request, new_user)
		return redirect("/")		
	context = {
		"form" : form,
		"title" : "Register",
		"subtitle": "Welcome My Site",
		"title2": "Register your account",
		"subtitle2": "Enter your Register",
		"controll" : '로그인',
		"controll_url" : "/login",
	}
	return render(request, "accounts.html", context)

def logout_view(request):
	logout(request)
	return redirect("/")

Django/Mysite/main/views.py
# -*- coding: utf-8 -*- 
from __future__ import unicode_literals
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from comments.forms import CommentForm
from comments.models import Comment
from .models import Post
from .forms import PostForm

@login_required(login_url='/login/')
def post_create(request):
	if request.user.is_authenticated():
		form = PostForm(request.POST or None, request.FILES or None)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.user=request.user
			instance.save()
			messages.success(request, "저장되었습니다.")
			return HttpResponseRedirect(instance.get_absolute_url())
		context = {
			"form":form,
		}
		return render(request, "post_form.html", context)
	else:
		return redirect("/")

def post_update(request, id=None):
	instance = get_object_or_404(Post, id=id)
	if (request.user == instance.user) or request.user.is_staff or request.user.is_superuser:
		form = PostForm(request.POST or None, request.FILES or None, instance=instance)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			messages.success(request, "<a href='#'>Item</a> Saved")
			return HttpResponseRedirect(instance.get_absolute_url())

		context = {
			"title": instance.title,
			"form":form,
			"instance": instance,
		}
		return render(request, "post_form.html", context)
	else:
		return redirect("/")


def post_detail(request, id=None):
	instance = get_object_or_404(Post, id=id)	
	initial_data = {
			"content_type":instance.get_content_type,
			"object_id":instance.id
	}
	form = CommentForm(request.POST or None, initial=initial_data)
	if form.is_valid() and request.user.is_authenticated():
		c_type = form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=c_type)
		obj_id = form.cleaned_data.get("object_id")
		content_data = form.cleaned_data.get("content")
		parent_obj = None
		try:
			parent_id = request.POST.get("parent_id")
		except:
			parent_id = None
		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count() == 1:
				parent_obj = parent_qs.first()

		new_comment, create = Comment.objects.get_or_create(
									user = request.user,
									content_type = content_type,
									object_id = obj_id,
									content = content_data,
									parent = parent_obj,
								)
		if create:
			return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

	comments = instance.comments
	context = {
		"title": instance.title,
		"instance": instance,
		"comments":comments,
		"comment_form":form,
	}
	return render(request, "post_detail.html", context)



def post_delete(request, id=None):
	instance = get_object_or_404(Post, id=id)
	if (request.user == instance.user) or request.user.is_staff or request.user.is_superuser:
		instance.delete()
		messages.success(request, "제거되었습니다.")
		return redirect("main:pmain")
	else:
		return redirect("/login/")

def post_main(request):
	query = request.GET.get("q")
	if not request.user.is_staff or not request.user.is_superuser:
		queryset_list = Post.objects.filter(~Q(classify__icontains = "문의"))
	else :
		queryset_list = Post.objects.all()
	if query:
		queryset_list = queryset_list.filter(
				Q(classify__icontains=query)|
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()

	paginator = Paginator(queryset_list, 30) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context = {
		"object_list": queryset,
		"page_request_var": page_request_var,
		"main":"메인",
		"computer":"컴퓨터",
		"chatting":"잡담",
		"drama":"드라마",
		"movie":"영화",
		"game":"게임",
		"suggest":"문의",
		"mylog":"내가쓴글",
		"value":"메인",
	}
	return render(request, "index.html", context)

def post_suggest(request):
	query = request.GET.get("q")
	queryset_list = Post.objects.filter(Q(classify__icontains = "문의"))
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 5) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context = {
		"object_list": queryset,
		"page_request_var": page_request_var,
		"main":"메인",
		"computer":"컴퓨터",
		"chatting":"잡담",
		"drama":"드라마",
		"movie":"영화",
		"game":"게임",
		"suggest":"문의",
		"mylog":"내가쓴글",
		"value":"문의",
	}
	return render(request, "index.html", context)

def post_chat(request):
	query = request.GET.get("q")
	queryset_list = Post.objects.filter(Q(classify__icontains = "잡담"))
	if query:
		queryset_list = queryset_list.filter(
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()
	paginator = Paginator(queryset_list, 5) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context = {
		"object_list": queryset,
		"page_request_var": page_request_var,
		"main":"메인",
		"computer":"컴퓨터",
		"chatting":"잡담",
		"drama":"드라마",
		"movie":"영화",
		"game":"게임",
		"suggest":"문의",
		"mylog":"내가쓴글",
		"value":"잡담",
	}
	return render(request, "index.html", context)


def post_computer(request):
	query = request.GET.get("q")
	queryset_list = Post.objects.filter(Q(classify__icontains = "컴퓨터"))
	
	if query:
		queryset_list = queryset_list.filter(
				Q(classify__icontains=query_c)&
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()

	paginator = Paginator(queryset_list, 25) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context = {
		"object_list": queryset,
		"page_request_var": page_request_var,
		"main":"메인",
		"computer":"컴퓨터",
		"chatting":"잡담",
		"drama":"드라마",
		"movie":"영화",
		"game":"게임",
		"suggest":"문의",
		"mylog":"내가쓴글",
		"value":"컴퓨터",
	}
	
	return render(request, "index.html", context)


def post_movie(request):
	query = request.GET.get("q")
	queryset_list = Post.objects.filter(Q(classify__icontains = "영화"))
	query_c = "영화"
	if query:
		queryset_list = queryset_list.filter(
				Q(classify__icontains=query_c)&
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()

	paginator = Paginator(queryset_list, 25) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context = {
		"object_list": queryset,
		"page_request_var": page_request_var,
		"main":"메인",
		"computer":"컴퓨터",
		"chatting":"잡담",
		"drama":"드라마",
		"movie":"영화",
		"game":"게임",
		"suggest":"문의",
		"mylog":"내가쓴글",
		"value":"영화",
	}
	return render(request, "index.html", context)

def post_game(request):
	query = request.GET.get("q")
	queryset_list = Post.objects.filter(Q(classify__icontains = "게임"))
	query_c = "게임"
	if query:
		queryset_list = queryset_list.filter(
				Q(classify__icontains=query_c)&
				Q(title__icontains=query)|
				Q(content__icontains=query)|
				Q(user__first_name__icontains=query) |
				Q(user__last_name__icontains=query)
				).distinct()

	paginator = Paginator(queryset_list, 25) # Show 25 contacts per page
	page_request_var = "page"
	page = request.GET.get(page_request_var)
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset = paginator.page(paginator.num_pages)
	context = {
		"object_list": queryset,
		"page_request_var": page_request_var,
		"main":"메인",
		"computer":"컴퓨터",
		"chatting":"잡담",
		"drama":"드라마",
		"movie":"영화",
		"game":"게임",
		"suggest":"문의",
		"mylog":"내가쓴글",
		"value":"게임",
	}
	return render(request, "index.html", context)

def post_drama(request):
	query = request.GET.get("q")
	queryset_list = Post.objects.filter(Q(classify__icontains = "드라마"))
	if query:

Django/Mysite/main/templates/accounts.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extra_head %}

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bootstrap Login Form Template</title>

        <!-- CSS -->
        <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:400,100,300,500">
        <link rel="stylesheet" href="/static/assets/bootstrap/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/assets/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="/static/assets/css/form-elements.css">
        <link rel="stylesheet" href="/static/assets/css/style.css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Favicon and touch icons -->
        <link rel="shortcut icon" href="assets/ico/favicon.png">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/static/assets/ico/apple-touch-icon-57-precomposed.png">

{% endblock extra_head %}

{% block content %}
        <!-- Top content -->
        <div class="top-content">
          
            <div class="inner-bg">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2 text">
                            <h1><strong>{{ title }}</strong></h1>
                            <div class="description">
                              <p>
                                {{ subtitle }}
                              </p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3 form-box">
                          <div class="form-top">
                            <div class="form-top-left">
                              <h3>{{ title2 }}</h3>
                                <p>{{ subtitle2 }}</p>
                            </div>
                            <div class="form-top-right">
                              <i class="fa fa-lock"></i>
                            </div>
                            </div>
                            <div class="form-bottom">
                          <form method='POST' action='' enctype='multipart/form-data' content='text/html; charset=UTF-8' class='login'>{% csrf_token %}
                              <div class="form-group">
                              {{ form|crispy }}
                              </div>
                              <div class="form-group">
                                <button type="submit" class="btn">Sign in!</button>
                              </div>

                                <a href="#" >비밀번호를 잊으셨습니까?</a><br>
                                <a href="{{ controll_url }}" >{{ controll }}</a>
                              
                          </form>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>


        <!-- Javascript -->
        <script src="/static/assets/js/jquery-1.11.1.min.js"></script>
        <script src="/static/assets/bootstrap/js/bootstrap.min.js"></script>
        <script src="/static/assets/js/jquery.backstretch.min.js"></script>
        <script src="/static/assets/js/scripts.js"></script>
        
        <!--[if lt IE 10]>
            <script src="assets/js/placeholder.js"></script>
        <![endif]-->


{% endblock content %}

Django/Mysite/main/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>

<html>
<head>
	<title>{% block head_title %}DoDomDom{% endblock head_title %}</title>

    {% block extra_head %}{% endblock extra_head %}
</head>
<body>
	<div class='container'>
		{% block content %}
			
		{% endblock content %}
	</div>
	
	

	<script
  		src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js">	
  	</script>

  	<script type="text/javascript">
  		$(document).ready(function(){
  			$(".content-markdown").each(function(){
	  			var content = $(this).text()
	  			var markedContent = marked(content)
	  			$(this).html(markedContent)
  			})
  			$(".post-detail-item img").each(function(){
	  			$(this).addClass("img-responsive");
	  		})

	  		

  			var contentInput = $("#id_content");

  			function setContent(value){
  				var markedContent = marked(value)
  				$("#preview-content").html(markedContent)
  				$("#preview-content img").each(function(){
  				$(this).addClass("img-responsive")
  				})
  			}
  			setContent(contentInput.val())

  			contentInput.keyup(function(){
  				var newContent = $(this).val()
  				setContent(newContent)
  			})

  			var titleInput = $("#id_title");

  			function setTitle(value){
  				$("#preview-title").text(value)
  			}
  			setTitle(titleInput.val())
  			titleInput.keyup(function(){
  				var newContent = $(this).val()
  				setTitle(newContent)
  			})

  		// preview-title
  		// preview-content
  		})



  	</script>
	
</body>
</html>